export const jokes = [
'¿Por qué el libro de matemáticas está triste? Porque tiene demasiados problemas.',
'¿Por qué fue el queso al hospital? Para ser un queso curado.',
'¿Qué le dice una impresora a otra? Esa hoja es tuya o es una impresion mia.',
'¿Cómo se llama un boomerang que no vuelve? Palo.',
'¿Qué le dice un techo a otro? Techo de menos.',
'¿Por qué la escoba llega tarde al trabajo? Porque se quedo barriendo.',
'¿Cual es el colmo de Aladin? Tener mal genio.',
'¿Qué hace una abeja en el gimnasio? Zum-ba.',
'¿Cómo se despiden los quimicos? Ácido un placer.',
'¿Qué hace un pez? Nada.',
'¿Qué le dijo una pared a la otra? Nos vemos en la esquina.',
'¿Cual es el animal mas antiguo? La cebra, porque esta en blanco y negro.',
'¿Por qué las focas miran siempre hacia arriba? Porque ahi estan los focos.',
'¿Qué le dice un techo a otro? Techo de menos.',
'¿Qué hace un perro con un taladro? Taladrando.',
'¿Qué le dice un semáforo a otro? No me mires que me estoy cambiando.',
'¿Qué hace una vaca cuando sale el sol? Sombra.',
'¿Cómo se llama un boomerang que no vuelve? Palo.',
'¿Qué le dice un gusano a otro? Voy a dar una vuelta a la manzana.',
'¿Qué hace un tomate en una carretera? Ketchup.',
'¿Cuál es el colmo de un jardinero? Que siempre lo dejen plantado.',
'¿Por qué el pollo cruzó la carretera? Para llegar al otro lado.',
'¿Qué hace un burro leyendo? Mejorando.',
'¿Qué hace una serpiente en una biblioteca? Sisea.',
'¿Por qué la luna va al gimnasio? Para cambiar de fase.',
'¿Qué hace una escoba corriendo? Barrer récords.',
'¿Qué hace una galleta en el hospital? Está hecha polvo.',
'¿Qué hace un pez con una calculadora? Nada, porque no sabe sumar.',
'¿Qué hace un mosquito con una guitarra? Música ligera.',
'¿Qué hace un tiburón con un megáfono? Da miedo amplificado.',
'¿Qué hace un murciélago con un móvil? Llamadas nocturnas.',
'¿Por qué el reloj se fue a terapia? Porque tenía tiempo de sobra.',
'¿Qué hace el fuego en una fiesta? Enciende el ambiente.',
'¿Qué hace una botella triste? Se siente vacía.',
'¿Por qué la foto fue a la cárcel? Por revelarse.',
'¿Qué hace una tortuga corriendo? Lo intenta.',
'¿Por qué el aire no discute? Porque pasa.',
'¿Qué hace una piedra aburrida? Nada.',
'¿Qué hace un mecánico limpio? Raro.',
'¿Cuál es el último animal que subió al Arca de Noé? El del-fin.',
'¿Qué hace un perro con un taladro? Taladrando.',
'¿Qué hace una vaca mirando las estrellas? ¡La Vía Láctea!',
'¿Qué le dice un huevo a una sartén? ¡Me tienes frito!',
'¿Qué le dice un pato a otro? Estamos empatados.',
'¿Cuál es el café más peligroso? El expreso',
'¿Qué le dice un cero a un ocho? ¡Qué cinturón más chulo!',
'A mí me gusta la gente abierta. -Eres el forense más tonto que conozco.',
'No sé por qué todas me miran el paquete. -Eres el repartidor de Amazon más tonto que conozco',
'Le llamo de Vodafone, le vamos a subir la fibra de 100 a 300Mb.. señora, ¿está llorando? -claro, me habéis tocado la fibra! ',
'¡Camarero, dos postres! -seis! ',
'Soy una máquina con las matemáticas. -¿una portenta? -¡treinta!',
'¿Has visto el trailer de Titanic? pero no era un barco?',
'Iba a contar un chiste sobre sodio... pero Na.',
'En Hawái no te hospedan: te alohan',
'¿Cómo se llama el padre de ET? Don ET',
'¿Cuales son los dibujos preferidos del capitan del Titanic? Timón y Pumba ',
'¿Cual es el peinado favorito de los carteros? Los tirabuzones',
'¿Qué hace un tupper en un bosque? Ta perdido',
'Un león se comió un jabón, y ahora es puma',
'¿Colmo de un peluquero? Descubrir que en la vida nada es permanente ',
'Robinson crusó, y fue atropellado',
'¿Cómo se llama el hermano limpio de Bruce Willis? Kevin Willis ',
'¿Cómo se despiden los químicos? Ácido un placer',
'Eliminar correos no deseados es muy fácil. Spam comido',
'¿Qué necesites un informático para bailar? algo-ritmo',
'¡Adóbame ese lomo! -lomo.pdf -¡sacad al informatico de la cocina!',
'Quise tener una novia programadora.... Pero no se de java',
'Hay 10 tipos de personas, los que entienden binario y los que no',
'Se abre un ascensor y dentro hay un informático, y le preguntan: ¿sube o baja? y contesta: ¡verdadero!',
'Un QA tester entra en un bar y pide 1 cerveza. Pide 0 cervezas. Pide 9999999 cervezas. Pide asdfgfdfgh cervezas. Pide -1 cervezas. Pide hola mundo cervezas. Al día siguiente el bar abre en producción. Entra un cliente y pregunta por el aseo; el bar arde en llamas y explota matando a todo el mundo.',
'Papá, por qué si el ordenador es tan listo que sabe que falta un punto y coma, por qué no lo añade él mismo?',
'¿Qué es una mujer objeto? Una instancia de una mujer con clase.',
' ¿Qué le menciona una IP a otra? ¿Qué tramas?.',
'¿Qué es un terapeuta? 1024 Gigapeutas.',
'¿Que le habla un bit al otro? Nos vemos en el bus.',
'¿Cuántos programadores hacen falta para cambiar una bombilla? Ninguno, porque es un problema hardware.',
'Se abre el telón, aparece un informático y dice: ¡qué habéis tocado que no se cierra el telón!.',
'¿Pero qué haces tirando esos ordenadores al río? -pero mira como beben los PC,s en el rió!.',
'Error 0094782: No se detecta ningún teclado pulse una tecla para continuar.',
'Están 1023 gigabytes en una fiesta, llega uno más y dice: ¿Nos hacemos un peta?.',
'¿Qué le dice un .GIF a un .JPEG? -Anímate viejo.',
'No te despedirán del trabajo, si nunca comentas tu código y además eres el único que sabe cómo funciona.',
'¿Cuál es la diferencia entre batman y Bill Gates? Que cuando batman luchó contra el pingüino ganó.',
'Dos programadores java charlando: «la excepción confirma la regla» «pues si hay una excepción, la capturamos».',
'Para qué quiere un pastor un compilador? pues para tener «OBEJOTAS».',
'La barriga de un programador es directamente proporcional a la cantidad de información que maneja.',
'Dios es real, a no ser que lo declares como integer.',
'Dos programadores dialogando sobre sus relaciones con su pareja: Yo tengo un vínculo muy fuerte con mi mujer. Entonces, tienes un hipervínculo?.',
'¿Y a ti cómo te va la vida sexual? \n-Pues como la Coca-Cola. \n-¿Como la Coca-Cola? \n-¿Y cómo es eso? \n-Primero normal, después light y ahora zero.',
'- Hola mi amor, ¿dónde estás? \n-En mi casa a punto de dormir, ¿Y tú?\n-En la discoteca detrás de tí.',
'La suegra con ganas de buscarle las cosquillas a la nuera le pregunta:\n-¿Por qué mi nieto no se parece a mi hijo?\nLa nuera le responde:\n-No sé... Yo tengo una vagina, no una fotocopiadora.',
'Tres viejitos hablan de como se duermen :\n-El 1° dice: Yo hago crucigramas.\n-El 2° dice: Yo veo y leo novelas.\n-Y el 3° dice: Yo me masturbo.\nY le preguntan los otros 2 viejitos asombrados:\n¿Y se te sube?\nNo, pero me canso y me duermo.',
'Hija: ¡Mamá, mamá! ¿Cómo se le dice a la mujer adicta al sexo?\nLa madre responde: Ninfómana hija...\nDéjame anotarlo porque los ignorantes del colegio me dicen puta.',
'Dos empleados del censo llegan a una casa y le preguntan:\n-¿Su nombre?\n-Adán.\n-¿Su esposa?\n-Eva.\n-¡Increíble! ¿Por casualidad la serpiente también vive aquí?\n-Sí, un momento. Suegraaaaaa..., la buscan.',
'SE ABRE EL TELÓN\nSe ve un rancho. Muchos caballos. Aparece un gitano.\nDesaparecen los caballos\nSE CIERRA EL TELÓN \n¿Cómo se llama la película?\nEL HOMBRE QUE SUS RUBABA LOS CABALLOS',
'Quién invento el triatlon?\nLos gitanos, que van a la piscina andando, y vuelven en bici',
'¿La consola que más le gusta a un gitano?\nLa Nintendo DE ESE...',
'⃣Esto es una madre gitana que llama a su hijo por la ventana:\n¡¡¡Benitoooo!!!\ny, vinieron todos',
'Nunca te rías de un gitano en bicicleta, porque podría ser la tuya',
'SE ABRE EL TELÓN\nUn cine lleno de gitanos.\nDos guardias civiles en la última fila.\nSE CIERRA EL TELÓN\n¿Cómo se llama la pelicula?\nLos últimos sus murais.',
'¿Como habéis llamado al niño?\n- Elengendro\n- Será Alejandro...\n- Es que tu no lo has visto...',
'Cariño ¿Quieres que pasemos los dos un fin de semana perfecto?\n- ¡Vale!\n- Pues nos vemos el lunes...',
'-Mira Mohamed, este es mi salón...\n- Hala, es grande...\n- Deja de rezar y escúchame...',
'A mi me han circuncidado...\n- ¿El Rabino?\n- No me seas cursi... la polla',
'-¿Que tal? ¿Nervioso?\n- Si, un poco...\n- ¿Es tu primera vez?\n- No, ya había estado nervioso antes...',
'- Venía por la oferta de trabajo...\n- ¿Habla usted inglés?\n- Si Señor...\n- ¿Nivel?\n- Level...',
'¿Ha visto usted como toca mi hijo el violín? ¿Que le parece su ejecución?\n- Hombre, ejecutarlo me parece excesivo, pero dos guantazos ya le daba...',
'- Mamá, ¿qué haces en frente de la computadora con los ojos cerrados?\n- Nada, hijo, es que Windows me dijo que cerrara las pestañas...',
'Le dice una madre a su hijo:\n- ¡Me ha dicho un pajarito que te drogas!\n- ¡La que se droga eres tu que hablas con pajaritos!',
'- Hola, ¿cómo te llamas?\n- María de Los Ángeles, ¿y tú?\n- Daniel de Nueva York',
'Se abre el telón, aparece un gitano, desaparece el telón.',
'¿Qué le dice una impresora a otra?\n¿Esta copia es tuya o es impresión mía?',
'- ¿Este vino de dónde es?\n- De Islandia, creo.\n- ¿No pone la ciudad?\n- Tetravrik.',
'- ¿Que hay para comer?\n- Una deconstrucción de huevo y patata crujiente al toque de ébano.\n- ¿Se te ha quemado la tortilla no?\n- Como un tizón.',
'- Pues hoy he echado un partido de basket con los amigos.\n- ¿y cómo habéis quedado?\n- Por Wathsapp.',
'- Sabes la carga del electrón?\n- Negativo.\n- Y la del protón?\n- Tampoco',
'- No sé si conseguiré enamorar a esa chica...\n- ¿Tienes vacas y ovejas?\n- Sí.\n- Pues ya tienes mucho ganado.',
'- El mes pasado contraí matrimonio\n- Contraje\n- No te jode. No iba a ser con chándal.',
'- Cuánto dura la batería del móvil?\n- Depende de la autonomía.\n- No sé...Pongamos Galicia, por ejemplo.',
'- Mi mujer me dijo que necesitaba más espacio.\n- ¿Y qué hiciste?\n- La regalé un disco duro de 2Tb',
'- ¿Quieres salir conmigo?\n- Mejor sal tú primero.',
'- Me puede decir la contraseña del Wifi de su bar?\n- Tómate una caña por lo menos, cabrón.\n- Todo junto?',
'-El otro día fuí a la panaderia y le pedí una de pan y si tenía huevos una docena......\ny salí con 12 barras de pan.',
'¡O te quitas esa falda tan corta o no sales!\n–¿Por qué, mamá?\n–Porque es muy corta.\n–¿Y quéeee?\n–¡¡¡Que se te ven los huevos, José Miguel!!!',
'–Eres la chica más simpática y más guapa que he conocido.\n–Tú lo que quieres es follar conmigo.\n–¡Coño! ¡¡¡Y la más lista!!!',
'–Por el culo no, Pepe.\n–Pues ya me dirás, Paco.',
'–Cariño, está lloviendo y sigues siendo una puta.\n–¿Y qué?\n–Me dijiste que con el tiempo cambiarias',
'–Perdí los resultados de la analítica... No sé si su esposo tenía SIDA o Alzheimer.\n–Entonces, ¿qué hago doctor?\n–Déjelo en un bosque, y si regresa no se lo folle.',
'–¿¿¿Qué queremos???\n–¡¡¡Quitar el autocorrector al iPhone!!!\n–¿¿¿Cuándo lo queremos???\n–¡Ahorca!\n–¡Ahorro!\n–¡Aborda!\n–¡Albora!\n–¡Su puta madre!',
'– Papá, ¿soy adoptado?\n– Te elegimos negro para no tener esta conversación.',
'–Cariño, ¿me engañas con otra?\n–Vale.',
'– Cariño, tengo un retraso.\n– Tranquila, tontita, que te quiero igual.',
'—Llevo un mes en el gimnasio.\n—¿Y tu familia no te echa de menos?',
'– Soy un noble caballero y sé cuando he de manchar con sangre mi espada.\n– Manolo, déjate de gilipolleces, que con la regla no follo.',
'– Te amo.\n– ¿Cómo sabes que es amor?\n– Porque pienso en ti y no puedo respirar.\n– Eso es asma.\n– Bueno, entonces te asmo.',
'–La paciencia es una virtud que pocos tienen.\n–¿Qué?\n–La paciencia es una virtud que pocos tienen.\n–¿Qué?\n–Que me cago en tu puta madre.',
'–Qué cabrón mi vecino. ¿Pues no se pone a llamar a mi puerta como un loco a las 4 de la mañana? Casi se me cae el taladro del susto.',
'– ¿Te parece bonito?\n– Sí.\n– Pues es rodaballo.\n– Vaya.',
'– Entonces, doctor, ¿con este condón de lana se curará mi impotencia? \n– No, pero le sudará la polla.',
'– Mamá, ¿cómo es que tú eres blanca, papá es negro y yo soy amarillo? \n– Hijo mío, si supieras la orgía que hubo aquel día… Agradece que no ladras.',
'Doctor, últimamente me encuentro más gordo y feo, ¿qué tengo?\n- Mucha razón. ',
'- ¿Qué tal acabaste anoche tío? \n- Pues guay, terminé follando con una americana.\n- ¡Que cabron! ¿Y que tal? \n- Pues muchísimo calor, tío...   tuve que quitármela.',
'- ¿Por qué no estais juntos?\n- Porque ella come amigos. \n- ¿Cómo que come amigos?\n- Sí, me dijo: "te quiero pero como amigos"',
'- ¿Cómo te va por el gimnasio? \n- ¡Brutal! Me salen músculos que ni siquiera conozco. Mira... ¿cómo se llamará éste?\n- Trapecio.\n- Yo a ti también,  tio, y mucho!!',
'- Me he liado con una sevillana y me ha llevado a ese sitio de bailar zapateaos.\n- ¿Tablao flamenco? \n- No, no. Habla español. Raro, pero español.',
'- Amor, está lloviendo y la ropa está tendida, ¿Me la metes?\n- Desde luego, cómo sois las mujeres… La ropa mojándose y tú solo pensando en follar.',
'- Ayer llamé a la Guardia Civil porque unos ladrones robaron en mi casa y se llevaron hasta los vasos. \n- ¿Y los detuvo? \n- Sí si, los de tubo y los de chupito.',
'- Mi mujer está gilipollas, me ha dejao una nota en el frigorífico donde pone: "me voy de casa porque esto no funciona". Y ya llevo dos horas mirándolo por todos sitios y esto enfría de puta madre.',
'- ¿De qué colegio eres? \n- Del Sagrado Corazón de Cristo Redentor y Santa María Vírgen Inmaculada Concepción.\n- Ya. Entonces de follar ni hablamos... ',
'- Lo de Armstrong estaba cantado. No se puede pisar la Luna, tocar bien la trompeta y Ganar 7 Tour de Francia, sin que nadie sospeche...',
'- Papá, ¿puedo usar el coche?\n- No, no puedes sin mi supervisión.\n- Uy! Perdón por no tener superpoderes como tú...',
'- Cariño, te veo mejor!\n- Pues estoy más gorda.\n-Pues eso, que te veo mejor...',
'- ¿Tú que opinas de las hipotecas?\n- A mí me parece cojonudo que los hipopótamos tengan un sitio para bailar.',
'- Niña, a donde vas con esas mallas?\n- Voy a aerobic.\n- Joder que coñazo!!\n- Sí, un rollo.\n-No, no me has entendido...',
'- Camarero! Este vino es horrible\n- Pero señor es un Ribera\n- Pues me debe de haber tocado Paquirrin',
'- Has visto el gol que ha marcado mi hijo?\n- El de penalti?\n- No el pequeño',
'-Doctor, a mi suegra le h salido una verruga\n-Ah, pues traigala y la quemamos\n-Madre mia doctor, me acaba usted de alegrar el dia',
'-Cariño, ha venido la vecina de arriba a pedir sal, que le digo?\n-Sal gorda?\n-Bien, me gusta, duro y directo. Voy\n-Que? Paco espera!!',
'-Jo tia! Que majo el chico de la disco de anoche, simpatico, atento...\n-Te lo follaste?\n-A su amigo',
'-Que maravilla el cuadro que tienes en esa pared!!\n-Es un Murillo\n-Bueno, pues en ese murillo',
'-Un placer venir a su mutua\n-es Mutuo\n-Un placer venir a su mutuo',
'-Sabias que las cajas negras de los aviones en realidad son naranjas?\n-¿qué dices, no son cajas?',
'-Joder con los mosquitos\n-Ponte repelente\n-Madre mia, que ingente cantidad de dipteros nematoceros',
'-Me han dicho que has estado en Cuba\n-Si, me encanto\n-Y el malecon,\n-Parecia una chica vale?',
'Cuando quiero saber que cosas me quedan por hacer, me tumbo en el sofa con el movil y mi mujer enseguida me lo recuerda',
'-Buenos dias, es esto el abismo?\n-que pasa que esta ciego? Esque no lo ve?\n-Si claro disculpe, y usted quien es?\n-El borde del abismo',
'-Buenas, tiene la pelicula llamada "Tu culo esta estacionado"?\n-Sabe el titulo en ingles?\n-Yourassispark',
'Si no pagas tus deudas con la tienda de fotografia, te mandan al fotomaton?',
'No paraban de gritarme: daltonico!! Y me puse rojo como un limon',
'-Te gustan mis gafas nuevas?\n-No demasiado\n-Son progresivas\n-Ah bueno, entonces ya me iran gustando',
'Una pequeña lección de historia:\nTal dia como hoy hace más de 500 años Cristobal Colon paseaba por los manglares cuando observó como unos indigenas se introducian una banana por el culo. Corroido por la curiosidad hizo lo mismo en la soledad de su camarote. A dia de hoy, a este tipo de prácticas anales se las conoce como COLON OS COPIA.',	
'Mamá, Pedrito está en la piscina, me puedo meter con él?\n-si hijo\n-Pedrito, cabrón!! joputaaaaaaaaa!!!!',
'Dr, cuando me drogo me noto ausente, como en otro mundo...\n-Abstraido?\n-sí, 2 gramos, quiere?',
'Oye, tú qué piensas de la gelatina?\n-ni idea! conozco la y griega y la i latina, pero no la g latina...',
'-qué tal el concurso de levitación para magos?\n-suspendido!\n-enhorabuena!!!',
'-Qué tal el concurso de tiro con arco para disléxicos?\n-certero\n-osea que ganaste! enhorabuena!\n-no no, que quedé el certero...',
'Mamá, ya sé de dónde viene mi nombre, es una construcción de una sola piedra, grande...\n-Cada día estás más tonto, Manolito.',
'Capitán hay un agujero en el barco!\n-rápido, llama al pirata Patapalo\n-¿para qué?\n-patapalo\n-jajajja\n-jajajajja, lo llamas o qué????',
'Mira un cohete!!!\n-Seguro que va a Venus!!!\n-Pos vamos a escondernus!!!',
'- ¿Es aquí la reunón de poetas violentos?\n- Sí aquí es, toma asiento\nY como hagas ruido te reviento.',
'- Aquí tiene su factura caballero.\n- ¿me la puede hacer en negro?\n- Yeah bitch, here is da bill, pay me madafacka',
'-bailas muy bien!\n-soy latina\n-encantado, yo soy el Braian',
'-qué te han traido los Reyes?\n-(con voz ahogada) una minicadena\n-y por qué lo dices así?\n-porque me aprieta mucho!',
'-papá, me voy a jugar al fútbol, dónde está mamá?\n-para qué la necesitas?\n-como siempre dices que te hincha las pelotas.... ',
'-Hijo te quiero hacer una pregunta...\n-Mamá, no soy gay\n-¿Cómo sabías que te iba a preguntar eso?\n-Intuición femenina, reina!',
'- Cariño, me puedes ir a por tampones?\n- Claro que si , los quieres con alas o sin alas?\n- Déjalo, ya voy yo',
'-tienen libros sobre el cansancio?\n-No, están todos agotados...',
'-Niiiiiiño, qué haces hablando con las alpargaaaaatas?\n-Ay paaaaaapa, que pone conveeeeeeeerse',
'- Capital de España?\n- La mayor parte en Suiza.',
'- ¿De qué signo es tu mujer?\n- Debe ser de exclamación, porque se pasa el día gritándome...',
'- ¿Me pone un zumo de piña?\n- ¿Natural…?\n- De Pontevedra, pero no creo que eso importe...',
'-Camarero, ponga una de calamares a la rumana.\n-Perdón, señor, será a la romana.\n-Irina, cariño, dile al sabiondo éste de dónde eres...',
'- La aceptas como esposa en la salud, en la enfermedad, en la riqueza y en la pobreza hasta que la muerte os separe?\n- Sí, no, si, no, no.',
'Siempre que mis padres me decían "estudia!" yo entendía "es tu día!", y salía de copas.',
'- Y vendes el piso?\n- Alquilo.\n- Y cuanto pesa?',
'¿Cómo está un mago después de comer? \nMagordito.',
'Tengo tres llamadas perdidas de mi oftalmólogo. El de ver me llama.',
'-Shhhhh. -Shhhhht. -Shhhhh. -Shhhhht. -Shhhhh. -Shhhhht. (Discusión entre una cobra y una bibliotecaria.)',
'Si la energía ni se crea ni se destruye, ¿QUE NOS ESTÁ COBRANDO IBERDROLA?',
'-¿Es grave Doctor?\n-¿Ha oído ese refrán que dice que lo que no mata engorda?\n-Sí.\n-Pues ha debido comer alguna cosa que no engorda.',
'-Hola, ¿es aquí el club de imbéciles?\n-Sí, pero... ¿qué hace con todo ese estiércol?\n-Vengo a abonarme.\n-Dios santo, pase, será el líder.',
'-Me da miedo ese deporte de las espadas.\n-¿Esgrima?\n-No, no, más bien es miedo.',
'-Me siento solo.\n-Yo también, sentarse es fácil.',
'-¿Me das una rebanadita de pastel? .. Pero así, súper chiquitita , que estoy a dieta.\n-¿Así, como las otras siete?.\n-Sí, porfa',
'-No te das cuenta pero ¡TE TENGO EN EL BOTE!\n-¡Deja de decir tonterías y REMA! ¡Subnormal!',
'Llega un tío a una tienda:\n-Tiene pan?\n-No\n-Tiene pan?\n-que no\n-Tiene pan?\n-que nooo. Y si me lo vuelves a preguntar te clavo la cabeza al suelo!!\n-Tiene clavos?\n-Tampoco!\n-y pan?',
'- Yo soy ateo.\n- Yo anolo, ucho gusto.\n- El gusto es ío',
'- ¡Puri! Quita la novela y pon el canal ese de letras que quiero ver la quiniela.\n- Te detesto Paco.\n- Eso, que no me acordaba como se dice',
'- Lo siento señora, pero no hemos podido hacer nada por su marido\n- ¿Por qué doctor?\n- Estaba drogado\n- Imposible, mi marido no se drogaba\n- Pero yo si',
'- Perdone, ¿es este el ascensor de subida?\n- No, he montado en otros mejores.',
'Llaman a la puerta y es un técnico del ayuntamiento.\n-Perdone, pero vamos a proceder al derribo del edificio contiguo.\n-¿Conmiguo?',
'-Me da un bote de yogur de ese líquido?\n-Yop?\n-Si,ustep!',
'- En ese bar te sirven unos callos increibles\n- Estan buenos?\n- Me referia a las camareras',
'-¿Te gustan más los Beatles o los Stones?\n-A mí me gustan los Doors.\n-Tienes que elegir uno.',
'- Me tienes harta Manolo ...solo piensas en comer!!!\n- A que te refieres croquetamente? ',
'-Doctor...estoy fatal, veo elefantes azules por todos los rincones...\n-Ya ha visto usted a algun psiquiatra?\n-No...de momento solo elefantes',
'- Ayer me dijeron que soy fea.\n- No te preocupes, a mí me han dicho cosas peores.\n- ¿Qué te han dicho?\n- Que también eres bastante puta.',
'- Chúpamela.\n- No.\n- Que me la chupesss.\n- Que nooo!!!\n- Ya bostezarás, ya....',
'- Hoy al salir del curro he atropellado un unicornio!!\n- No jodas!! Tienes curro??',
'- ¿Tú en que trabajas?\n- Soy inventor: la rueda, la penicilina, la radio...\n- Eso es mentira!!\n- Ya ves, me lo he inventado todo.',
'- Eres tan fea que sólo te guiñan los ojos los francotiradores.',
'- ¿Dónde van los esquimales de putas?\n- Al putiglú.',
'- Me gusta tu disfraz de vaca.\n- Voy de dálmata.\n- Ah...,',
'- Hijo tu te drogas ???\n- No mama.\n- Es que como al peinarte te haces la raya con la Visa.',
 '- Manoli, ¿por qué lloras?\n- La cebolla.\n- Es por el Sulfóxido de tiopropanal.\n- ¡Joooder Pepe! y que luego no te acuerdes de nuestro aniversario...',
'- Peláez, espero que haya estudiado para el examen de historia\n- No lo dude, profe \n- Hábleme de Tercer Reich\n- Ese fue el que llevó mirra, ¿no?',
'- Cariño, creo que tienes un problema con el juego.\n- ¿Yo? ¿Por qué?\n- En sueños gritas:¡Tragaperra! ¡Tragaperra!\n- Ah! Sí, sí, estoy muy enganchado. ',
'- Peláez ¿ha llegado el informe de balística?\n- Sí, jefe.\n- ¿Y qué dice?\n- Que somos mongolos, que murió de un hachazo.',
'- ¿Hay orcos cerca Frodo? Tu espada brilla mucho.\n- Aparque en el arcén; no hace falta ni que sople.',
'- Venía a revisar esta rueda; dice mi mujer que se desgasta muy rápido.\n- Estará desequilibrada\n- Está como una puta regadera, como su madre...',
'- Papá, ¿soy adoptado?\n- ¿Tú crees que te habríamos elegido a ti?',
 '- Cariño, no puedo dormir.\n- ¿Y te jodía que yo sí? ',
'- Cuaderno de bitácora. Fecha estelar 2334. El alien trata de dar a luz una nueva criatura.\n- Paco, por Dios, deja a mi madre cagar tranquila.',
' ...porque siempre  es bueno ampliar el vocabulario... \nINESTABLE: Mesa  norteamericana de Inés.\nONDEANDO: Donde estoy.\nCAMARÓN: Aparato  enorme que saca fotos.\nDECIMAL:  Pronunciar equivocadamente.\nBECERRO: Que  ve u observa una loma o colina.\nBERMUDAS: Observar  a las que no hablan.\nTELEPATÍA: aparato  de TV para la hermana de mi  mamá.\nTELÓN: Tela  de 50 metros ... o más.\nANÓMALO:  Hemorroides.\nBARBARISMO: Colección  exagerada de muñecas barbie.\nPOLINESIA: Mujer  Policía que no quiere entender   nada.\nCHINCHILLA:  Auchenchia de un lugar para  chentarche.\nDIADEMAS:  Veintinueve de febrero.\nDILEMAS: Háblale  más.\nMANIFIESTA: Juerga de  cacahuetes.\nMEOLLO: Me  escucho.\nATIBORRARTE:  Desaparecerte.\nCACHIBACHE: Pequeño  hoyo en el pavimento que está a punto de  convertirse en Bache.\nENDOSCOPIO: Me  preparo para todos los exámenes excepto para  dos.\nNITRATO: Ni lo  intento..\nNUEVAMENTE: Cerebro  sin usar.\nTALENTO: No ta  rápido.\nESGUINCE: Uno más que gatorce.\nESMALTE: Ni lune  ni miélcole..\nSORPRENDIDA: Monja en llamas',
'- Ayer llamé a la Guardia Civil porque unos rumanos robaron en mi casa y se llevaron hasta los vasos.\n- ¿Y los detuvo?\n- Sí sí, los de tubo y los de chupito.',
'- Me he liado con una sevillana y me ha llevado a ese sitio de bailar zapateaos.\n- ¿Tablao flamenco?\n- No, no. Habla español. Raro, pero español.',
'- ¿Cómo te va por el gimnasio?\n- ¡Brutal! Me salen músculos que ni siquiera conozco. Mira... ¿cómo se llamará este?\n- Trapecio.\n- Yo a ti también, tío, y mucho!',
'¿Cómo se dice suegra en chino?\nLin - chen - la',
'- Papá, papá, ¿Qué es robar?\nCalla y sigue corriendo. ',
'- Soy virgen, lo juro por mis hijos. ',
'- ¿Qué le dijo un timbre a un dedo?\nSi me tocas, grito. ',
'- ¿Alo? Habla Dora.\n¿Habladora? ¡Habladora tu hermana!', 
'- ¿Cuál es la formula del agua bendita?\nHDiosO. ',
'- Si estudiar es un camino, copiarse es un atajo. ',
'- ¿Cómo se dice espejo en japonés?\nHai toi. ',
'- Doctor, doctor, tengo un hueso afuera.\nHágalo pasar. ',
'- ¿Cómo se dice suegra en ruso?\nKela Rrifen. ',
'- ¿Cuál es el santo más fuerte?\nSan Son.',
'- ¿Cómo se dice misterio en Chino?\nChacha cha chan... ',
'- ¿Cuál es el lápiz que mata?\nLapiz-tola. ',
'- ¿Cómo se dice pobre en chino?\nChin unchentavo. ',
'- ¿Dónde cuelga Superman su ropa ?\nEn superchero. ',
'- ¿Qué es un asterisco?\nUn punto electrocutado. ',
'CÓMO SE DICE...EN CHINO?\nPelo sucio= chin-champú\nPobre= chin lú, chin agua y chin gá\nHuérfano= chinchupale chinchumale\nHombre delgado= fla ku ching\nViudo= chin chu concha\nHombre que tiene frío= chin chu poncho\nZapato sucio= tafuchi tuchancla\nDescalzo= chin chinela',
'CÓMO SE DICE...EN JAPONÉS...?\nElectricista= yokito fokito\nAdivino= komosabe\nAl contado= taka-taka\nBombero= ataka layama\nCoche roto= tu toyota taroto\nBomba atómica= nikaka keda\nCafé amargo= takara lazukar\nDiarrea= kagasagua\nEspejo= ai toi\nHemorroides= tukulito sakayama\nMe robaron la moto= yanoveo miyamaha',
'CÓMO SE DICE...EN ÁRABE...?\nAmetralladora= alla va la bala atajala\nBésame= mojame lajeta\nDiarrea= alud al-kagar',
'CÓMO SE DICE...EN ALEMÁN...?\nSuegra= ajjjjj\nAbrir la puerta= destranken\n40 años de casados= jodansen',
'CÓMO SE DICE...EN GUARANÍ...?\nCaminaré= andaré porai\nDeber dinero= yatepagaré\nDetective= averiguaré porai\nMe voy a ir= mepiraré',
'CÓMO SE DICE...EN FRANCÉS...?\nDesnudo= se la ví\nTuve cien hijos= parisienne',
'CÓMO SE DICE...EN ZULÚ...?\nCreo que estoy embarazada= bombo supongo\nDiarrea = abunda lacaca\nHicieron trampa en el casino= ubotongo enlatimba',
];

export function getRandomJoke(exclude?: string): string {
  const candidates = exclude ? jokes.filter((joke) => joke !== exclude) : jokes;
  if (candidates.length === 0) {
    return jokes[0];
  }
  const randomIndex = Math.floor(Math.random() * candidates.length);
  return candidates[randomIndex];
}

function shuffle<T>(arr: T[]): T[] {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
}

export function getJokesSequence(count: number): string[] {
  if (count <= 0) return [];

  let deck = shuffle(jokes);
  const sequence: string[] = [];

  while (sequence.length < count) {
    if (deck.length === 0) {
      deck = shuffle(jokes);
    }

    const next = deck.shift()!;

    if (sequence.length > 0 && next === sequence[sequence.length - 1]) {
      // Avoid repeating the same joke back-to-back when decks wrap.
      deck.push(next);
      continue;
    }

    sequence.push(next);
  }

  return sequence;
}
